---
title: "mGPS - MetaSUB New York microbiome results and figures"
author: "Leo McCarthy and Eran Elhaik"
output:
  html_document:
    df_print: paged
---

```{r setup, echo = F}

### path to mGPS top-level directory here ###
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(fig.width=13, fig.height=8) 
```

```{r, message = F}
NYDataPreds <- read.csv("Metasub/Outputs/NY/ny_results.csv")

library(geosphere)
library(randomcoloR) 
library(mapplots)
library(tidyr)
library(reshape2)
library(viridis)
library(rworldmap)
library(ggplot2)
library(maps)

```

```{r}
#Extract and rank species importance
v <- read.csv("Metasub/Outputs/NY/ny_git.csv")
top_species <- v[1:25,"taxa"]

#plot

par(font = 3)
dotchart(rev(v[1:25,"Overall"])*100,labels= rev(top_species),cex=1.2,pt.cex = 1.3,
         xlab="Mean decrease in accuracy", mgp = c(2.2,0,0))


```


```{r}
####plot ####
new_york_stations <- read.csv("Data/Geo/NYstations.csv",header = TRUE)
new_york_stations <- new_york_stations[!duplicated(new_york_stations$Station),]
new_york_stations$Station <- make.names(new_york_stations$Station)

NY_stations_set <- new_york_stations[ new_york_stations$Station %in% c(levels(NYDataPreds$station)) ,]
NY_stations_set <- droplevels(NY_stations_set[order(NY_stations_set$Latitude),])
lats_of_stations <- NY_stations_set$Latitude


#### borough ####

NYshp <- rgdal::readOGR(dsn = "Data/Geo/Borough Boundaries", layer = "geo_export_7935534f-c2ad-409d-980f-0f435898722e", verbose = FALSE)
NYBorough <- rgdal::readOGR(dsn = "Data/Geo/Borough Boundaries (Water Areas Included)", layer = "geo_export_830a0aea-d1d1-43f6-8349-8c576c70d38e", verbose = FALSE)
NYlines <- rgdal::readOGR(dsn = "Data/Geo/Subway Lines", layer = "geo_export_a9654720-1ef7-4794-97d4-b5424f827c02", verbose = FALSE)

find_borough <- function(long,lat){
  
  
  
  if(point.in.polygon(long,lat, SpatialPolygons2map(NYBorough[1,])$x,SpatialPolygons2map(NYBorough[1,])$y) %in% c(1,2,3)){
    borough <- NYBorough[1,]$boro_name
  }
  
  else if(point.in.polygon(long,lat, SpatialPolygons2map(NYBorough[2,])$x,SpatialPolygons2map(NYBorough[2,])$y)%in% c(1,2,3)){
    borough <- NYBorough[2,]$boro_name
  
  }
  else if(point.in.polygon(long,lat, SpatialPolygons2map(NYBorough[3,])$x,SpatialPolygons2map(NYBorough[3,])$y) %in% c(1,2,3)){
    borough <- NYBorough[3,]$boro_name
  }
  else if(point.in.polygon(long,lat, SpatialPolygons2map(NYBorough[4,])$x,SpatialPolygons2map(NYBorough[4,])$y)%in% c(1,2,3)){
    borough <- NYBorough[4,]$boro_name
  }
  
  else if(point.in.polygon(long,lat, SpatialPolygons2map(NYBorough[5,])$x,SpatialPolygons2map(NYBorough[5,])$y)%in% c(1,2,3)){
    borough <- NYBorough[5,]$boro_name
  }
  
  return(borough)
}

NYDataPreds[,"Borough"] <- droplevels(mapply(find_borough, NYDataPreds$longitude,NYDataPreds$latitude))
NYDataPreds[,"PredBorough"] <- droplevels(mapply(find_borough, NYDataPreds$longPred,NYDataPreds$latPred))
#mean(NYDataPreds$PredBorough == NYDataPreds$Borough)



#Ds]istance from origin
for (i in 1:nrow(NYDataPreds)){
  NYDataPreds[i,"Distance_from_origin"] <- 
    distm(c(NYDataPreds[i,"longPred"],NYDataPreds[i,"latPred"]), c(NYDataPreds[i,"longitude"],NYDataPreds[i,"latitude"]), fun = distHaversine)/1000
}
print( paste("Median distance form origin (km), " ,median(NYDataPreds[,"Distance_from_origin"] )))



#Plotting Fig 3, will be saved to working directory 
pie_lats <- c(40.6819,40.737,40.7319)
pie_longs <- c(-73.967,-74.055,-73.84)
palette <-c( "gold2","darkorchid4","deeppink2")

#png("Fig3.png", width = 12, height = 8, units = 'in', res = 600)
plot(NYshp ,xlim = c(-74,-73.85),ylim = c(40.67,40.8),col = "grey", xlab ="",ylab ="", bg= "lightskyblue1", lwd = 1.2,border = "grey40")
title(ylab="Latitude",xlab = "Longitude", mgp=c(2,1,0),cex.lab=1.2)
lines(NYlines, col = "brown3", cex = 0.8)
for (i in 1:3){
  this_borough <- levels(NYDataPreds$Borough)[i]
  stations <- levels(droplevels(NYDataPreds[NYDataPreds$Borough == this_borough,"station"]))
  
  find_lats <- NYDataPreds[NYDataPreds[,"Borough"] == this_borough,]$latPred
  find_longs <- NYDataPreds[NYDataPreds[,"Borough"] == this_borough,]$longPred
  
  station_lat <- NY_stations_set[NY_stations_set[,"Station"] %in% stations,]$Latitude
  station_long <- NY_stations_set[NY_stations_set[,"Station"] %in% stations,]$Longitude
  
  points(find_longs,find_lats, col = palette[i], pch  = "+", cex = 1.3)
  points(station_long,station_lat, col = palette[i], pch  = 17, cex = 1.6)
  
  correct <- mean(NYDataPreds[NYDataPreds$Borough == this_borough,"PredBorough"] == this_borough)
  add.pie(z = c(correct,1-correct) , x = pie_longs[i], 
          y = pie_lats[i], radius = 0.01, col = c(palette[i],"black"), labels = "")

  
}
for (i in 1:3){
  this_borough <- levels(NYDataPreds$Borough)[i]
  label_lats <- c(-73.94,-74.028,-73.815)
  text(label_lats[i],pie_lats[i] ,labels = this_borough, col = palette[i], font = 2)
}
legend(-74.08,40.85,legend = c("Stations","Predicted sample locations"),pch = c(17,3),col ="darkgreen", cex = 0.7)
map.axes(cex.axis = 0.8)
map.scale( cex = 0.5)
par(fig = c(0,0.3,0.5,1), new = T) 
plot(NYshp,col = "grey", bg ="lightskyblue1",border = "grey40")
points(NYDataPreds$city_longitude, NYDataPreds$city_latitude, cex = 1.5, pch = 16)
text(-73.95,40.68, labels = "New York", pch = 1.35, font = 2)
rect(-74.1, 40.6 ,-73.8, 40.8, density = NULL, angle = 45,
     col = NA, border = NULL, pch = 2)
box( col = 'black')

#dev.off()
```
```{r, message = F}

# abund station plot 
levels(NYDataPreds$station)[levels(NYDataPreds$station)=="Brooklyn.Bridge.City.Hall.Chambers.St"] <- "City.Hall.Chambers.St"
levels(NYDataPreds$station)[levels(NYDataPreds$station)=="Sutphin.Blvd.Archer.Av...JFK" ] <- "Sutphin.Blvd.Archer.Av" 
ag <-  aggregate(NYDataPreds[,as.character(top_species)], by = list(NYDataPreds$station), FUN = median)




for (i in top_species){
  ag[,i] <- (ag[,i] - min(ag[,i]))/(max(ag[,i]) - min(ag[,i]))
}
data.long <- melt(ag)


ggplot(data = data.long, mapping = aes(x = Group.1,
                                       y = forcats::fct_rev(variable),
                                       fill = value)) +
  geom_tile()+
  scale_fill_viridis(begin = 0, end = 1, limits = c(0,1)) +
  xlab("Station")+
  ylab("")+
  labs(fill="Relative abundance \n(normalised)")+
 theme(axis.text.x = element_text(angle = 45,vjust = 1, hjust = 1, size = 11),
       axis.text.y=element_text(size = 12, face = "italic"),
       legend.text = element_text(size = 11), 
       legend.title = element_text(size = 12))


# ggsave(
#   "NY_FigS13.png",
#   plot = last_plot(),
#   device = NULL,
#   path = NULL,
#   scale = 1,
#   width = 13,
#   height = 8,
#   
#   dpi = 600,
#   limitsize = TRUE)


```