---
title: "mGPS - MetaSUB London microbiome results and figures"
author: "Leo McCarthy and Eran Elhaik"
output: 
  github_document
    
---

```{r setup, echo = F}

### path to mGPS top-level directory here ###
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(fig.width=13, fig.height=8) 
```

```{r, message = F}
LDNDataPreds <- read.csv("Metasub/Outputs/LDN/ldn_results.csv")

library(geosphere)
library(randomcoloR) 
library(mapplots)
library(tidyr)
library(reshape2)
library(viridis)
library(rworldmap)
library(ggplot2)

```


```{r}
#Extract and rank species importance
v <- read.csv("Metasub/Outputs/LDN/ldn_git.csv")
top_species <- v[1:25,"taxa"]

#plot

par(font = 3)
dotchart(rev(v[1:25,"Overall"])*100,labels= rev(top_species),cex=1.2,pt.cex = 1.3,
         xlab="Mean decrease in accuracy", mgp = c(2.2,0,0))

```


```{r, message =F, warning = F}
#Plotting
london_stations <- read.csv(file = "Data/Geo/London stations GPS.csv", header = TRUE)

ldn_stations_set <- london_stations[ london_stations$Station %in% c(levels(LDNDataPreds$station)) ,]
ldn_stations_set <-droplevels( ldn_stations_set[order(ldn_stations_set$Latitude),])

lats_of_stations <- aggregate(LDNDataPreds$latitude, by = list(LDNDataPreds$super_station), FUN = mean)


### generate a colour platte,one colour per station, colours get lighter as the latitude of the station increases#### 
cols <- colorRampPalette(c("darkgreen", "orange"))
n <- length(levels(LDNDataPreds$super_station))
palette <- cols(n)[as.numeric(cut(lats_of_stations$x,breaks = n))]
ldn_line <- rgdal::readOGR(dsn ="Data/Geo/LondonRail",layer = "Tracks", verbose = F)


#palette <- palette <-c( "gold2","brown","dodgerblue3","darkorchid4","orangered2","olivedrab2","deeppink2","mediumspringgreen", "gray21","cyan2")
london_stations[,"Station"] <- make.names(london_stations[,"Station"])


#png("LdnPreds.png", width = 12, height = 8, units = 'in', res = 600)
map <- getMap(resolution = "high")
plot(map,xlim = c(-.5,.2), ylim = c(51.42,51.62), col = "grey", bg = "lightskyblue1",border = "darkgrey")
title(ylab="Latitude",xlab = "Longitude", mgp=c(2,1,0),cex.lab=1.2)
lines(ldn_line, col = "brown3")


for (i in 1:nlevels(LDNDataPreds$super_station)){
  this_station<- levels(LDNDataPreds$super_station)[i]
  find_lats <- LDNDataPreds[LDNDataPreds[,"super_station"] == this_station,]$latPred
  find_longs <- LDNDataPreds[LDNDataPreds[,"super_station"] == this_station,]$longPred
  
  st <- levels(droplevels(LDNDataPreds[LDNDataPreds[,"super_station"] == this_station,]$station))
  points(ldn_stations_set[ldn_stations_set[,"Station"] %in% st,]$Longitude, ldn_stations_set[ldn_stations_set[,"Station"] %in% st,]$Latitude, col = palette[i],bg = palette[i], pch = 17, cex = 1.5)
  #points(LDNDataPreds[LDNDataPreds[,"station"] == this_station,]$longitude, LDNDataPreds[LDNDataPreds[,"station"] == this_station,]$latitude, col = palette[i], pch = 19, cex = 0.6)
  points(find_longs, find_lats, col = palette[i], pch = "+", cex = 1.5)
  
}
#legend(-0.465,51.45, legend = c("Stations","Sample predictions"), col = c(palette),pch = c(17,3),box.lty= 1, cex = 1.2, bg = "lightsteelblue1")
axis(1); axis(2)
par(fig = c(0,0.3,0.5,1), new = T) 
plot(map,xlim = c(-1,1), ylim = c(50,53), col = "grey", bg ="lightskyblue1",border = "grey40")
points(LDNDataPreds$city_longitude, LDNDataPreds$city_latitude, cex = 1, pch = 16)
text(LDNDataPreds$city_longitude+1.2,LDNDataPreds$city_latitude, labels = "London", pch = 1.35, font = 2, cex = 0.8)
rect(-0.12574-0.5, 51.50853-0.3 ,-0.12574+0.5, 51.50853+0.3, density = NULL, angle = 45,
     col = NA, border = NULL, pch = 2)
box( col = 'black')

#dev.off()


```

```{r}
for (i in 1:nrow(LDNDataPreds)){
  LDNDataPreds[i,"Distance_from_origin"] <- distm(c(LDNDataPreds[i,"longPred"],LDNDataPreds[i,"latPred"]), c(LDNDataPreds[i,"longitude"],LDNDataPreds[i,"latitude"]), fun = distHaversine)/1000
}
print(paste("median distance from origin (km) = ", median(LDNDataPreds$Distance_from_origin)))
```

```{r, message = F}

#Abundance by station plot for fig s13, will be saved to working directory 
levels(LDNDataPreds$super_station) <- c("R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10","R11","R12","R13","R14","R15")
ag <-  aggregate(LDNDataPreds[,as.character(top_species)], by = list(LDNDataPreds$super_station), FUN = median)


for (i in top_species){
  ag[,i] <- (ag[,i] - min(ag[,i]))/(max(ag[,i]) - min(ag[,i]))
}


data.long <- melt(ag)

ggplot(data = data.long, mapping = aes(x = Group.1,
                                       y = forcats::fct_rev(variable),
                                       fill = value)) +
  geom_tile()+
  scale_fill_viridis(limits = c(0,1)) +
  xlab("Region")+
  ylab("")+
  theme(axis.text.x = element_text(angle = 45,vjust = 1, hjust = 1, size = 11),
        axis.text.y=element_text(size = 12, face = "italic"),
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 12),
        axis.title.x = element_text(size = 12))+
  labs(fill="Relative abundance \n(normalised)")
  #theme(axis.text.x = element_text( hjust = 1))
  

# ggsave(
#   "LDN_FigS13.png",
#   plot = last_plot(),
#   device = NULL,
#   path = NULL,
#   scale = 1,
#   width = 14,
#   height = 8,
#   
#   dpi = 600,
#   limitsize = TRUE,)
```