---
title: "mGPS - MetaSUB Hong Kong microbiome results and figures"
output: 
  github_document
    
---

```{r setup, echo = F}

### path to mGPS top-level directory here ###
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(fig.width=13, fig.height=8) 
```

```{r, message = F, echo = T}
HkDataPreds <- read.csv("Metasub/Outputs/HK/hk_results.csv")
library(geosphere)
library(randomcoloR) 
library(mapplots)
library(tidyr)
library(ggplot2)
#library(hrbrthemes)
library(reshape2)
library(viridis)
library(rworldmap)
library(maps)
```


```{r}
#Extract and rank species importance
v <- read.csv("Metasub/Outputs/HK/hk_git.csv")
top_species <- v[1:25,"taxa"]

#plot

par(font = 3)
dotchart(rev(v[1:25,"Overall"])*100,labels= rev(top_species),cex=1.2,pt.cex = 1.3,
         xlab="Mean decrease in accuracy", mgp = c(2.2,0,0))

```



```{r}
HKshp <- rgdal::readOGR(dsn ="Data/Geo/gadm36_HKG_shp", layer = "gadm36_HKG_1", verbose = F)
station_names <- c("Admiralty"     ,"Che Kung Temple"  ,  "Cheung Chau",       
"Cheung Sha Wan"   ,  "East Tsim Sha Tsui", "Fo Tan",            
"Fortress Hill"   ,   "Hung Hom"       ,    "Kowloon Tong" ,     
"Lai King",           "Mongkok East",       "North Point"     ,  
"Peng Chau",          "Prince Edward",      "Quarry Bay" ,       
"Residence 1",        "Residence 2",        "Residence 3",       
"Residence 4",        "Sai Kung",           "Sai Wan Ho Pier",   
"Sham Shui Po",       "Shek Kip Mei",       "Tai Mei Tuk",       
"Tai O",              "Tai Wai",            "Tsim Sha Tsui",     
"Tsing Yi",           "Tuen Mun Pier",      "Wan Chai",          
"Wu Kai Sha Pier",    "Yau Tong",           "Yung Shue Wan") 
#Get distance from origin 
for (i in 1:nrow(HkDataPreds)){
  HkDataPreds[i,"Distance_from_origin"] <- distm(c(HkDataPreds[i,"longPred"],HkDataPreds[i,"latPred"]), c(HkDataPreds[i,"longitude"],HkDataPreds[i,"latitude"]), fun = distHaversine)/1000
}

#postResample(HkDataPreds$latitude, HkDataPreds$latPred)
print(paste("Median distance from origin (km) = ", median(HkDataPreds$Distance_from_origin)))
##Plots Fig S4 will be saved to working directory


#color palette 
n <- length(levels(HkDataPreds$station))
set.seed(15)
palette <- randomColor(count = n, luminosity = "bright")

#plot predicted GPS locations
map <- getMap(resolution = "high")
palette <- randomColor(count = n, luminosity = "bright")
#png("FigS4.png", width = 12, height = 8, units = 'in', res = 600)
plot(HKshp,xlim = c(114,114.2), ylim = c(22.17,22.47), col = "grey",border = "darkgrey", bg = "lightskyblue1", xlab = "", ylab = "")
title(ylab="Latitude",xlab = "Longitude", mgp=c(2,1,0),cex.lab=1.2)
for (i in 1:length(levels(HkDataPreds$station))){
  this_station<- levels(HkDataPreds$station)[i]
  find_lats <- HkDataPreds[HkDataPreds[,"station"] == this_station,]$latPred
  find_longs <- HkDataPreds[HkDataPreds[,"station"] == this_station,]$longPred
  points(find_longs, find_lats, col = palette[i], pch = "+", cex = 1.5)
  
}
#plot station locations
for (i in 1:length(levels(HkDataPreds$station))){
  this_station<- levels(HkDataPreds$station)[i]
  
  station_lat <- mean(HkDataPreds[HkDataPreds$station == this_station,]$latitude)
  station_long <- mean(HkDataPreds[HkDataPreds$station == this_station,]$longitude)
  
  points(station_long, station_lat, col = "black", bg =palette[i] ,pch = 24, cex = 1.3)
}
#legend 
legend(114.3,22.45,legend=station_names, col = palette,pch = 17, cex = 0.8, bg = "lightskyblue1")
map.axes(cex.axis = 0.8)
map.scale( cex = 1)
#inset map 
par(fig = c(0,0.3,0.5,1), new = T) 
plot(map,xlim = c(110,116), ylim = c(22.15,22.45), col = "grey", bg ="lightskyblue1",border = "darkgrey")
points(HkDataPreds$city_longitude, HkDataPreds$city_latitude,pch = 16)
text(114.175,22.05, labels = "Hong Kong", pch = 2, cex = 0.8, font = 2)
rect(113.15, 21.4 ,115.2, 23.1, density = NULL, angle = 45,
     col = NA, border = NULL, pch = 2)
box( col = 'black')
#dev.off()

```

```{r}


## Fig 2 - , will be saved to working directory

find_island <- function(long,lat){
  ### generate west island coords
  #west_lats <- SpatialPolygons2map(HKshp[3,])$y
  #west_longs <- SpatialPolygons2map(HKshp[3,])$x
  
  north_lats <- SpatialPolygons2map(HKshp[c(4:10,12:14,16:18),])$y
  north_longs <- SpatialPolygons2map(HKshp[c(4:10,12:14,16:18),])$x
  
  south_lats <- SpatialPolygons2map(HKshp[c(11,1:2,15),])$y
  south_longs <- SpatialPolygons2map(HKshp[c(11,1:2,15),])$x
  
  west_lats <- SpatialPolygons2map(HKshp[3,])$y
  west_longs <- SpatialPolygons2map(HKshp[3,])$x
  
  if(lat > 22.4){
    island <- "North"
  }
  
  else if(point.in.polygon(long,lat,north_longs,north_lats) %in% c(1,2,3)){
    island <- "North"
  }
  else if(point.in.polygon(long,lat,south_longs,south_lats) %in% c(1,2,3)){
    island <- "South"
  }
  else if(point.in.polygon(long,lat,west_longs,west_lats) %in% c(1,2,3)){
    island <- "West"
  }
  else {
    island <- "None"
  }
  return(island)
}


HkDataPreds$Island <- factor(mapply(find_island, long = HkDataPreds$longitude, lat = HkDataPreds$latitude))
HkDataPreds$predIsland <- factor(mapply(find_island, long = HkDataPreds$longPred, lat =HkDataPreds$latPred))
HkDataPreds <-  droplevels(HkDataPreds[HkDataPreds$predIsland != "None",])


#mean(HkDataPreds$Island == HkDataPreds$predIsland)

#png("Fig2.png", width = 12, height = 8, units = 'in', res = 600)
plot(HKshp,xlim = c(114.15,114.15), ylim = c(22.17,22.47), col = "grey", border = "darkgrey",bg = "lightskyblue1", xlab = "",ylab = "")
title(ylab="Latitude",xlab = "Longitude", mgp=c(2,1,0),cex.lab=1.2)
for (i in 1:length(levels(HkDataPreds$station))){
  this_station<- levels(HkDataPreds$station)[i]
  
  station_lat <- mean(HkDataPreds[HkDataPreds$station == this_station,]$latitude)
  station_long <- mean(HkDataPreds[HkDataPreds$station == this_station,]$longitude)
  
  
  correctly_predicted <- mean(HkDataPreds[HkDataPreds$station == this_station,]$stationPred == this_station ) 
  correct_island <- mean(HkDataPreds[HkDataPreds$station == this_station,]$predIsland == HkDataPreds[HkDataPreds$station == this_station,]$Island
                         & HkDataPreds[HkDataPreds$station == this_station,]$stationPred != this_station)
                           
  incorrectly_predicted <- (1 - (correctly_predicted + correct_island) ) 
  
  
  add.pie( x = station_long,y = station_lat, z = c(correctly_predicted,correct_island,incorrectly_predicted)
               ,edges=200,
               radius=0.012*(1-(1/length(HkDataPreds[HkDataPreds$station == this_station,]$stationPred)**0.5)),
               col=c("red","white","black"), labels = ""
  )
  
}




map.axes(cex.axis = 1)
map.scale( cex = 1)
par(fig = c(0.625,0.975,0.1,0.65), new = T) 
plot(HKshp,xlim = c(114.185,114.2), ylim = c(22.265,22.345), col = "grey", border = "darkgrey", bg ="lightskyblue1")
box( col = 'black')
for (i in 1:length(levels(HkDataPreds$station))){
  this_station<- levels(HkDataPreds$station)[i]
  
  station_lat <- mean(HkDataPreds[HkDataPreds$station == this_station,]$latitude)
  station_long <- mean(HkDataPreds[HkDataPreds$station == this_station,]$longitude)
  
  
  correctly_predicted <- mean(HkDataPreds[HkDataPreds$station == this_station,]$stationPred == this_station ) 
  correct_island <- mean(HkDataPreds[HkDataPreds$station == this_station,]$predIsland == HkDataPreds[HkDataPreds$station == this_station,]$Island
                         & HkDataPreds[HkDataPreds$station == this_station,]$stationPred != this_station)
  
  incorrectly_predicted <- (1 - (correctly_predicted + correct_island) ) 
  
  
  add.pie( x = station_long,y = station_lat, z = c(correctly_predicted,correct_island,incorrectly_predicted)
           ,edges=200,
           radius=0.012*(1-(1/length(HkDataPreds[HkDataPreds$station == this_station,]$stationPred)**0.25)),
           col=c("red","white","black"), labels = ""
  )
  
}

#dev.off()


```

```{r, message = F}

# Fig S13, will be saved to working directory
levels(HkDataPreds$station) <- station_names


ag <-  aggregate(HkDataPreds[,as.character(top_species)], by = list(HkDataPreds$station), FUN = median)
for (i in top_species){
  
  ag[,i] <- ag[,i] <- (ag[,i] - min(ag[,i]))/(max(ag[,i]) - min(ag[,i]))
}
data.long <- melt(ag)


ggplot(data = data.long, mapping = aes(x = Group.1,
                                       y =forcats::fct_rev(variable),
                                       fill = value)) +
  geom_tile()+
  scale_fill_viridis(limits = c(0,1)) +
  xlab("Station")+
  ylab("")+
  labs(fill="Relative abundance \n(normalised)")+
  theme(axis.text.x = element_text(angle = 45,vjust = 1, hjust = 1, size = 11),
        axis.text.y=element_text(size = 12, face = "italic"),
        
        legend.text = element_text(size = 11), 
        legend.title = element_text(size = 12))

# ggsave(
#   "Hk_FigS13.png",
#   plot = last_plot(),
#   device = NULL,
#   path = NULL,
#   scale = 1,
#   width = 13,
#   height = 8,
#   
#   dpi = 600,
#   limitsize = TRUE)


```






